build:
  command: "pip install -r requirements.txt"
  runtime: python-3.12

services:
  - type: web
    name: streamlit-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port $PORT
    port: 8501
    scaling:
      min_instances: 1
      max_instances: 1
